export const Permissions = {
    UserProfileProfileCreate: "userprofile.profile.create",
    UserProfileProfileRead: "userprofile.profile.read",
    UserProfileProfileUpdate: "userprofile.profile.update",
    UserProfileProfileDelete: "userprofile.profile.delete",
    UserProfileAdditionalInfoCreate: "userprofile.additionalinfo.create",
    UserProfileAdditionalInfoRead: "userprofile.additionalinfo.read",
    UserProfileAdditionalInfoUpdate: "userprofile.additionalinfo.update",
    UserProfileAdditionalInfoDelete: "userprofile.additionalinfo.delete",
    UserProfilePhotoCreate: "userprofile.photo.create",
    UserProfilePhotoRead: "userprofile.photo.read",
    UserProfilePhotoDelete: "userprofile.photo.delete",

    BillingBalanceRead: "billing.balance.read",
    BillingDebtRead: "billing.debt.read",
    BillingTransactionCreate: "billing.transaction.create",
    BillingTransactionRead: "billing.transaction.read",
    BillingPaymentInitialize: "billing.payment.initialize",
    BillingPaymentHistoryRead: "billing.payment.read",

    VenueTariffCreate: "venue.tariff.create",
    VenueTariffRead: "venue.tariff.read",
    VenueTariffUpdate: "venue.tariff.update",
    VenueTariffDelete: "venue.tariff.delete",
    VenueTariffActivate: "venue.tariff.activate",
    VenueTariffDeactivate: "venue.tariff.deactivate",
    VenuePromotionCreate: "venue.promotion.create",
    VenuePromotionRead: "venue.promotion.read",
    VenuePromotionUpdate: "venue.promotion.update",
    VenuePromotionDelete: "venue.promotion.delete",
    VenuePromotionActivate: "venue.promotion.activate",
    VenuePromotionDeactivate: "venue.promotion.deactivate",
    VenueThemeCreate: "venue.theme.create",
    VenueThemeRead: "venue.theme.read",
    VenueThemeUpdate: "venue.theme.update",
    VenueThemeDelete: "venue.theme.delete",
    VenueVisitCreate: "venue.visit.create",
    VenueVisitRead: "venue.visit.read",
    VenueVisitUpdate: "venue.visit.update",
    VenueVisitDelete: "venue.visit.delete",
    VenueVisitEnd: "venue.visit.end",

    AccountSelfRead: "auth.account.self.read",
    AccountAdminRead: "auth.account.admin.read",
    AccountEmailChange: "auth.account.email.change",
    AccountPasswordChange: "auth.account.password.change",
    AccountPhoneSave: "auth.account.phone.save",
    AccountPhoneClear: "auth.account.phone.clear",
    AccountPhoneGenerate: "auth.account.phone.generate",
    AccountPhoneVerify: "auth.account.phone.verify",
    AccountPhoneStatusRead: "auth.account.phone.status.read",

    RbacRoleCreate: "auth.rbac.role.create",
    RbacRoleRead: "auth.rbac.role.read",
    RbacRoleUpdate: "auth.rbac.role.update",
    RbacRoleDelete: "auth.rbac.role.delete",
    RbacRoleClaimsUpdate: "auth.rbac.role.claims.update",
    RbacPermissionRead: "auth.rbac.permission.read",
    RbacUserRoleAssign: "auth.rbac.userrole.assign",
    RbacUserRoleRemove: "auth.rbac.userrole.remove",
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];

export const AdminPanelPermission = Permissions.AccountAdminRead;
