global using System.Net;
global using System.Net.Http.Json;
global using FluentAssertions;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Caching.Hybrid;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Moq;
global using UserProfile.TimeCafe.Application.CQRS.AdditionalInfos.Commands;
global using UserProfile.TimeCafe.Application.CQRS.AdditionalInfos.Events;
global using UserProfile.TimeCafe.Application.CQRS.AdditionalInfos.Queries;
global using UserProfile.TimeCafe.Application.CQRS.Photos.Commands;
global using UserProfile.TimeCafe.Application.CQRS.Photos.Queries;
global using UserProfile.TimeCafe.Application.CQRS.Profiles.Commands;
global using UserProfile.TimeCafe.Application.CQRS.Profiles.Events;
global using UserProfile.TimeCafe.Application.CQRS.Profiles.Queries;
global using UserProfile.TimeCafe.Domain.Contracts;
global using UserProfile.TimeCafe.Domain.Enums;
global using UserProfile.TimeCafe.Domain.Errors;
global using UserProfile.TimeCafe.Domain.Models;
global using UserProfile.TimeCafe.Infrastructure.Data;
global using UserProfile.TimeCafe.Test.Integration.Helpers;
global using Xunit;
global using static UserProfile.TimeCafe.Test.Integration.Helpers.TestData;
global using IUnitOfWork = UserProfile.TimeCafe.Application.Contracts.IUnitOfWork;
