global using Auth.TimeCafe.Application.DTO;
global using Auth.TimeCafe.Infrastructure.Data;
global using Auth.TimeCafe.Infrastructure.Services;
global using Auth.TimeCafe.Domain.Models;
global using Auth.TimeCafe.Domain.Services;
global using Carter;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Swashbuckle.AspNetCore.Filters;
